version: '3.8'

services:
  backend:
    image: instartech/backend:instardeco
    restart: always
    env_file:
      - .env
    ports:
      - "9001:9000"  # Mappe le port 9000 du conteneur sur le port 9001 de l'hôte
    depends_on:
      - mongodb
    volumes:
      - ./uploads:/app/uploads  # Monte le dossier uploads de l'hôte vers le conteneur
    command: sh -c "chown -R node:node /app/uploads && npm start"  # Ajuste les permissions avant de démarrer

  mongodb:
    image: mongo:6.0
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: instar
    ports:
      - "27017:27017"  # Mappe le port MongoDB du conteneur sur le port 27017 de l'hôte
    volumes:
      - mongodb_data:/data/db  # Volume pour la persistance des données MongoDB

volumes:
  mongodb_data:
    driver: local  # Volume persistant pour MongoDB
