version: '3.7'

services:
  backend:
    image: instartech/backend:instardeco
    restart: always
    env_file:
      - .env
    ports:
      - "9002:9000"  
    depends_on:
      - mongodb
    volumes:
      - uploads_volume:/app/uploads
    user: "appuser:appgroup"
    entrypoint: ["node", "./prod-build/server.js"]

  mongodb:
    image: mongo:6.0
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: instar
      MONGO_INITDB_DATABASE: indar-deco
    ports:
      - "27018:27017"  
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
    driver: local
  uploads_volume:
    driver: local