version: '3.7'

services:
  backend:
    image: instartech/backend:instardeco
    restart: always
    env_file:
      - .env  # Utilisation du fichier .env pour charger les variables d'environnement
    ports:
      - "9001:9000"  # Mapping host port 9001 to container port 9000
    depends_on:
      - mongodb  # Dépendance sur MongoDB
    volumes:
      - uploads_volume:/app/uploads  # Assurez-vous que ce chemin correspond à votre dossier de fichiers statiques
    user: "appuser:appgroup"  # Définir l'utilisateur et le groupe
    entrypoint: ["node", "./prod-build/server.js"]  # Point d'entrée du backend
    # Un script comme 'wait-for-it' peut être utilisé pour attendre MongoDB avant de démarrer le backend si nécessaire

  mongodb:
    image: mongo:6.0
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}  # Utilisation de la variable d'environnement DB_USER
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASS}  # Utilisation de la variable d'environnement DB_PASS
    ports:
      - "27017:27017"  # Exposition de MongoDB sur le port par défaut
    volumes:
      - mongodb_data:/data/db  # Montée du volume de données MongoDB

volumes:
  mongodb_data:
    driver: local
  uploads_volume:
    driver: local
