apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: "{{ .Values.backend.image }}"
          ports:
            - containerPort: {{ .Values.backend.port }}
          envFrom:
            - configMapRef:
                name: backend-config
          volumeMounts:
            - mountPath: "{{ .Values.backend.volume.path }}"
              name: uploads
      volumes:
        - name: uploads
          persistentVolumeClaim:
            claimName: uploads-volume
      restartPolicy: Always