apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      securityContext:
        fsGroup: 1000  # Définir le groupe propriétaire du volume
      initContainers:
        - name: volume-permission-fix
          image: busybox
          command: ["sh", "-c", "chown -R 1000:1000 {{ .Values.backend.volume.path }}"]
          volumeMounts:
            - mountPath: "{{ .Values.backend.volume.path }}"
              name: uploads
      containers:
        - name: backend
          image: "{{ .Values.backend.image }}"
          ports:
            - containerPort: {{ .Values.backend.port }}
          envFrom:
            - configMapRef:
                name: backend-config
          volumeMounts:
            - mountPath: "{{ .Values.backend.volume.path }}"
              name: uploads
      volumes:
        - name: uploads
          persistentVolumeClaim:
            claimName: uploads-volume
      restartPolicy: Always