apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  labels:
    app: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: "{{ .Values.mongodb.image }}"
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: "{{ .Values.mongodb.rootUser }}"
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: "{{ .Values.mongodb.rootPassword }}"
            - name: MONGO_INITDB_DATABASE
              value: "{{ .Values.mongodb.database }}"
          ports:
            - containerPort: {{ .Values.mongodb.port }}
          volumeMounts:
            - mountPath: "{{ .Values.mongodb.volume.path }}"
              name: mongodb-data
      volumes:
        - name: mongodb-data
          persistentVolumeClaim:
            claimName: mongodb-data
      restartPolicy: Always