version: '3'
services:
  node-app:
    container_name: indar_deco_node_container
    ports:
      - "9000:9000"
    env_file:
      ./.env 
    
  mongo:
    image: mongo
    restart: always
    volumes:
      - mongo-db:/data/db
    container_name: mongo-server
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: instar_indar_deco
      MONGO_INITDB_ROOT_PASSWORD: indarDeco2024
  
volumes:
  mongo-db: